version: '3.1'

services:
  postgres:
    image: postgres:13
    container_name: ${ENV_DEPLOY}-${APP_NAME}-db-postgres
    command: >
      -c max_connections=1000 -c shared_buffers=1GB
    restart: always
    ports:
      - "${DB_PORT_MOUNT}:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhtaidang
      POSTGRES_DB: anhtaidang
    env_file:
      - .env
    volumes:
      - ./data/${ENV_DEPLOY}-db-postgres:/var/lib/postgresql/data
    networks:
      - app-network
  db-redis-a:
    image: redis:alpine
    container_name: ${ENV_DEPLOY}-${APP_NAME}-db-redis-a
    restart: always
    ports:
      - "${REDIS_PORT_MOUNT_A}:6379"
    volumes:
      - ./data/${ENV_DEPLOY}-db-redis-a:/data
    env_file:
      - .env
    networks:
      - app-network
  db-redis-b:
    image: redis:alpine
    container_name: ${ENV_DEPLOY}-${APP_NAME}-db-redis-b
    restart: always
    ports:
      - "${REDIS_PORT_MOUNT_B}:6379"
    volumes:
      - ./data/${ENV_DEPLOY}-db-redis-b:/data
    env_file:
      - .env
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${ENV_DEPLOY}-${APP_NAME}-rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_PORT_MOUNT}:5672"
      - "${RABBITMQ_MGT_PORT_MOUNT}:15672"
    volumes:
      - ./data/${ENV_DEPLOY}-${APP_NAME}-rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    name: ${ENV_DEPLOY}-${APP_NAME}-app-network
    driver: bridge
    ipam:
      driver: default
