name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Thiết lập SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Print GitHub environment variables
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Branch/Tag: $GITHUB_REF"
        echo "Commit SHA: $GITHUB_SHA"
        echo "CHECK ${{ vars.DOCKER_IMPLEMENT_PATH }}"
    
    - name: RUN SUDO APT
      run: |
        docker --version

    # Copy docker-compose.yml lên VPS
    - name: Copy docker-compose.yml to VPS
      run: |
        scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:${{ env.DOCKER_IMPLEMENT_PATH }}
        scp -o StrictHostKeyChecking=no .env ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:${{ env.DOCKER_IMPLEMENT_PATH }}

    # Connect SSH & RUN docker-compose
    - name: Deploy application with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
        echo "CD to ${{ vars.DOCKER_PATH }}"
        cd ${{ vars.DOCKER_PATH }}
        ls -a
        docker-compose up -d --build
        EOF
